# Generated by Django 3.2 on 2021-05-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0021_deviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvite',
            name='with_slack',
            field=models.BooleanField(default=False),
        ),
    ]
